### ISSUE TITLE
Wercker build fails

### ISSUE THREAD

**Issue by CalvinMcGee** [EdgecaseInc/wercker-step-install-aws-cli#5]
I'm getting the following when trying to install aws cli:

`Traceback (most recent call last):
  File "./awscli-bundle/install", line 138, in <module>
    main()
  File "./awscli-bundle/install", line 129, in main
Running cmd: /usr/bin/python virtualenv.py --python /usr/bin/python /usr/local/aws
Running cmd: /usr/local/aws/bin/pip install --no-index --find-links file:///pipeline/source/awscli-bundle/packages awscli-1.11.21.tar.gz
    pip_install_packages(opts.install_dir)
  File "./awscli-bundle/install", line 98, in pip_install_packages
    pip_script, PACKAGES_DIR, cli_tarball))
  File "./awscli-bundle/install", line 44, in run
    p.returncode, cmd, stdout + stderr))
__main__.BadRCError: Bad rc (1) for cmd '/usr/local/aws/bin/pip install --no-index --find-links file:///pipeline/source/awscli-bundle/packages awscli-1.11.21.tar.gz': Processing ./awscli-1.11.21.tar.gz
`

And I get the following when trying to use the aws-cli:

`/pipeline/script-f8745800-db0f-4d8f-a785-f475d075d2ef/run.sh: line 2: aws: command not found`

**Comment by CalvinMcGee** [comment]
It seems to be because of this issue: https://github.com/aws/aws-cli/issues/2290

**Comment by CalvinMcGee** [comment]
Pull request: https://github.com/EdgecaseInc/wercker-step-install-aws-cli/pull/6 should solve this issue
